FROM node:16-alpine

RUN mkdir -p /app

WORKDIR app/

ADD package*.json /app/
ADD dist/ /app/dist/

RUN npm ci --only=production

ENV NODE_ENV=${NODE_ENV}
ENV API_ENDPOINT=${API_ENDPOINT}

EXPOSE 3000

RUN npm start
