FROM node:16-alpine

RUN mkdir -p /app

WORKDIR app/

ADD package*.json /app/
ADD build/ /app/build/

RUN npm ci --only=production

ENV NODE_ENV=${NODE_ENV}
ENV G_CLIENT_ID=${G_CLIENT_ID}

EXPOSE 3000

RUN npm start
