FROM node:16-alpine

RUN mkdir -p /app

WORKDIR app/

ADD package*.json /app/
ADD dist/ /app/dist/

RUN npm ci --only=production

ENV NODE_ENV=${NODE_ENV}
ENV MONGO_URL=${MONGO_URL}
ENV G_CLIENT_ID=${G_CLIENT_ID}
ENV USER=${USER}
ENV PASSWORD=${PASSWORD}

RUN npm start
