name: Run build and test pipeline

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    if: github.event.pull_request.draft == false

    env:
      POSTGRES_USER: pg
      POSTGRES_PASSWORD: postgres
      POSTGRES_DATABASE: buystuff4me
      POSTGRES_URL: postgresql://pg:postgres@localhost:5432/buystuff4me

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - name: Cache node modules
        uses: actions/cache@v2
        env:
          cache-name: cache-node-modules
        with:
          # npm cache files are stored in `~/.npm` on Linux/macOS
          path: ~/.npm
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install modules
        run:
          npm install && cd api && npm install && cd ../frontend && npm install

      - name: Eslint
        run: npm run lint:api && npm run lint:frontend

      - name: Build project
        run: cd api && npm build && cd ../frontend && npm build

      - name: Test
        run: npm run coverage --if-present

#      - name: Upload coverage to Codecov
#        uses: codecov/codecov-action@v2
#        with:
#          token: ${{ secrets.CODECOV_TOKEN}}
